version: '3.8'

services:
  php:
    image: php:fpm-alpine3.12
    volumes:
      - './:/usr/src/app'

  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - './:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - php
